#!/bin/sh
NO_ARG=0
E_ERR_OPZ=65

if [ $# -eq "$NO_ARG" ] # Chck for argument
then
  echo "Using: `basename $0` module_name"
  exit $E_ERR_OPZ # Quit and report error number
fi

MODULENAME=$1

# Create folder
mkdir $MODULENAME
mkdir $MODULENAME/translation
mkdir $MODULENAME/tests

# Create file
touch $MODULENAME/README
touch $MODULENAME/INSTALL
echo  "info_init"    > $MODULENAME/$MODULENAME.info
echo  "install_init" > $MODULENAME/$MODULENAME.install
echo  "module_init"  > $MODULENAME/$MODULENAME.module

# Open file whit gedit
gedit $MODULENAME/$MODULENAME.info \
      $MODULENAME/$MODULENAME.install \
      $MODULENAME/$MODULENAME.module
