#!/bin/sh
NO_ARG=0
E_ERR_OPZ=65

if [ $# -eq "$NO_ARG" ] # Chck for argument
then
  echo "Using: `basename $0` module_name"
  exit $E_ERR_OPZ # Quit and report error number
fi

MODULENAME=$1

# Create folder
mkdir $MODULENAME
mkdir $MODULENAME/translation
mkdir $MODULENAME/tests

# Create file
touch $MODULENAME/README
touch $MODULENAME/INSTALL
echo  "initinfo"    > $MODULENAME/$MODULENAME.info
echo  "initinstall" > $MODULENAME/$MODULENAME.install
echo  "initmodule"  > $MODULENAME/$MODULENAME.module

# Open file whit gedit
gedit $MODULENAME/$MODULENAME.info \
      $MODULENAME/$MODULENAME.install \
      $MODULENAME/$MODULENAME.module
